### ISSUE TITLE
I did not get the Graphs Builder plugin 

### ISSUE THREAD

**Issue by VladimirLevadnij** [surgeharb/strapi-plugin-graphs-builder#1]
Hello. I did everything according to the instructions, but I did not get the Graphs Builder plugin. Please tell me what can be done? :-)

`yarn add strapi-plugin-graphs-builder`
`yarn build`
`yarn develop` or `yarn develop --watch-admin`

![image](https://user-images.githubusercontent.com/20191527/144688334-ed423e7e-5238-4827-a091-8ae9116338b5.png)

Version:

![image](https://user-images.githubusercontent.com/20191527/144688502-def4045e-1f69-4dc7-ad03-d058b533285b.png)

**Comment by VladimirLevadnij** [comment]
It is not in the list of plugins.

![image](https://user-images.githubusercontent.com/20191527/144689029-adb98bb7-a72a-4838-957d-41dee64a3e54.png)

But it is in the folder node_modules.

![image](https://user-images.githubusercontent.com/20191527/144689064-fb0553c5-9d48-4ffb-b3cf-0e4b8cfd0d53.png)

**Comment by surgeharb** [comment]
This can be easily fixed by adding the following to the `package.json` to enable "Automatic Plugin Discovery"
```js
"strapi": {
  "kind": "plugin"
}
```
